// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_weather_app_clean/test/data/repositories/auto_complete_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter_weather_app_clean/domain/interfaces/network/api_client.dart'
    as _i4;
import 'package:flutter_weather_app_clean/domain/interfaces/network/network_info.dart'
    as _i2;
import 'package:flutter_weather_app_clean/foundation/failures/failure.dart'
    as _i6;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkInfo_0 extends _i1.SmartFake implements _i2.NetworkInfo {
  _FakeNetworkInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  @override
  _i2.NetworkInfo get networkInfo => (super.noSuchMethod(
        Invocation.getter(#networkInfo),
        returnValue: _FakeNetworkInfo_0(
          this,
          Invocation.getter(#networkInfo),
        ),
        returnValueForMissingStub: _FakeNetworkInfo_0(
          this,
          Invocation.getter(#networkInfo),
        ),
      ) as _i2.NetworkInfo);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Response>> getReq(Uri? uri) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReq,
          [uri],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Response>>.value(
            _FakeEither_1<_i6.Failure, _i7.Response>(
          this,
          Invocation.method(
            #getReq,
            [uri],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.Response>>.value(
                _FakeEither_1<_i6.Failure, _i7.Response>(
          this,
          Invocation.method(
            #getReq,
            [uri],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Response>>);
}
